name: tabler_icons_next
description: Yet another Tabler Icons package for Flutter that keeps updating with the latest version of the upstream.
homepage: https://tabler-icons-next.betakuang.me/
repository: https://github.com/beta/tabler_icons_next

version: 3.30.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
