name: gallery
description: Gallery app for Table Icons Next.
publish_to: 'none'

version: 3.17.4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  package_info_plus: ^4.1.0
  tabler_icons_next:
    path: ..
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
